### ISSUE TITLE
Allow defining multiple `env_keys` for one input/output

### ISSUE THREAD

**Issue by PaulKalho** [RWTH-TIME/scystream-sdk#11]
It will likely occur that an input or output can be configured/defined by not one, but multiple `env_keys`.

At the moment this is not possible.

Consider the following:

```yaml
name: "NLP toolbox"
description: "Contains NLP algorithms..."
author: "John Doe"
docker_image: "https://ghcr.io/nlp-toolbox"

entrypoints:
  topic_modelling:
    description: "Run topic modelling"
    inputs:
      db_data_one:
        description: "DB data in a selfhosted database"
        type: "db_table"
        table_name: "not_nlp_info"
        optional: True
      db_data_two:
        description: "Information in a database"
        type: "db_table"
        env_key: "DATA_TABLE_NAME"
        table_name: "nlp_information"
        optional: True
```

What if the input db_data_one is self-hosted and the host should also be configurable from the outside. We'd then need to be able to pass other information like the DB_HOST and DB_PORT to the input config.

With this change we could also think about renaming the key (`env_key`) to something like `config_vars`
