### ISSUE TITLE
`cbc.yaml` null values in configs & envs should be typed

### ISSUE THREAD

**Issue by PaulKalho** [RWTH-TIME/scystream-sdk#19]
If a config/env has no default value, the `cbc.yaml` currently does not expose the type of this key.

This is needed within the core application. Therefore we should extend the current cbc schema by that.

An example:

```yaml
...
envs:
  TEST_ENV: null
      type: str
  ANOTHER_ONE: "hallo"
  IS_TRUE: null
      type: bool
```
