### ISSUE TITLE
typo in documentation

### ISSUE THREAD

**Issue by PaulKalho** [RWTH-TIME/scystream-sdk#20]
In the first shown `cbc.yaml` there is an issue wih the yaml formatting.

```yaml
 inputs:
      pg_input:
      description: "Postgres input example"
      type: "db_table"
      config:
        PG_USER: "postgres"
        PG_PASS: "postgres"
        PG_HOST: "postgres"
        TABLE_NAME: "example_table"
```
